### ISSUE TITLE
Todo 2017/9

### ISSUE THREAD

**Issue by shinshin86** [shinshin86/readblet#1]
- [ ] Register to npm repository
- [ ] Update to README
- [ ] Update to test
